// Build assets/voice/timings.js and index.html from assets/voice/timings.json.
// Run after scripts/voice.mjs. Usage: node scripts/layout.mjs
import { readFileSync, writeFileSync } from "node:fs";

const OFFSET = 0.6; // silence before the voice starts
const LEAD = 0.5; // a scene starts this long before its first word
const HOLD = 1.6; // hold on the last frame after the voice ends
const data = JSON.parse(readFileSync("assets/voice/timings.json", "utf8"));

// Scene start times, in video seconds. A scene never cuts the last word of the one before it.
const starts = data.scenes.map((s, i) => {
  if (i === 0) return 0;
  const prevEnd = data.scenes[i - 1].words.at(-1).end + OFFSET;
  return Math.max(prevEnd + 0.06, s.words[0].start + OFFSET - LEAD);
});
const total = +(data.seconds + OFFSET + HOLD).toFixed(3);
const scenes = data.scenes.map((s, i) => {
  const start = +starts[i].toFixed(3);
  const end = i + 1 < starts.length ? starts[i + 1] : total;
  return {
    n: s.n,
    start,
    dur: +(end - start).toFixed(3),
    // Word times are relative to the scene start.
    words: s.words.map((w) => ({ w: w.w, start: +(w.start + OFFSET - start).toFixed(3), end: +(w.end + OFFSET - start).toFixed(3) })),
  };
});

writeFileSync(
  "assets/voice/timings.js",
  "// Generated by scripts/layout.mjs. Do not edit.\nwindow.TIMINGS = " + JSON.stringify({ total, scenes }) + ";\n",
);

const hosts = scenes
  .map(
    (s) =>
      `      <div id="s${s.n}" class="clip" data-composition-id="s${s.n}" data-composition-src="compositions/s${s.n}.html" data-start="${s.start}" data-duration="${s.dur}" data-track-index="1" data-width="1920" data-height="1080"></div>`,
  )
  .join("\n");

const html = `<!doctype html>
<html lang="en" data-resolution="landscape">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>Set up 1Password for Walleterm</title>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <link rel="stylesheet" href="assets/base.css" />
    <script src="assets/voice/timings.js"></script>
    <script src="assets/scene.js"></script>
    <style>
      #root { position: relative; width: 100%; height: 100%; overflow: hidden; background: var(--paper); }
      #moon { position: absolute; left: 1450px; top: -260px; width: 760px; height: 760px; border-radius: 50%; background: var(--moon); }
      #hill { position: absolute; left: -200px; top: 900px; width: 1500px; height: 700px; border-radius: 50%; background: var(--moss); opacity: 0.22; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-width="1920" data-height="1080" data-duration="${total}">
      <div id="moon" data-layout-allow-overflow></div>
      <div id="hill" data-layout-allow-overflow></div>
${hosts}
      <audio id="voice" src="assets/voice/narration.mp3" data-start="${OFFSET}" data-duration="${data.seconds.toFixed(3)}" data-track-index="10" data-volume="1"></audio>
    </div>
    <script>
      const tl = gsap.timeline({ paused: true });
      tl.fromTo("#moon", { y: 0 }, { y: 40, duration: ${total}, ease: "sine.inOut" }, 0);
      tl.fromTo("#hill", { x: 0 }, { x: 60, duration: ${total}, ease: "sine.inOut" }, 0);
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
`;
writeFileSync("index.html", html);
console.log(`total ${total}s`, scenes.map((s) => `${s.n}@${s.start}+${s.dur}`).join(" "));
