import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const result = await build({ absWorkingDir: root, entryPoints: ['demo/site/syntax.js'], bundle: true,
  format: 'esm', platform: 'browser', target: 'es2022', minify: true, write: false,
  banner: { js: '// Generated by npm run build:syntax. Twinkleplop 0.1.5 / core 0.2.2; MIT license in syntax.LICENSE.' } });
const target = new URL('../demo/site/vendor/syntax.js', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== result.outputFiles[0].text) throw Error('Run npm run build:syntax and commit the updated bundle.');
} else await writeFile(target, result.outputFiles[0].text);
